"""Human-readable passphrase code generator and validator."""

import secrets
from typing import Tuple

ADJECTIVES = [
    "amber",
    "ancient",
    "arctic",
    "azure",
    "bold",
    "brave",
    "bright",
    "bronze",
    "calm",
    "cedar",
    "clever",
    "cobalt",
    "copper",
    "coral",
    "crimson",
    "crystal",
    "daring",
    "dawn",
    "deep",
    "dusk",
    "eager",
    "early",
    "ember",
    "emerald",
    "fair",
    "fast",
    "fierce",
    "flint",
    "forest",
    "frost",
    "gentle",
    "golden",
    "grand",
    "green",
    "grey",
    "happy",
    "hardy",
    "hasty",
    "hazel",
    "heavy",
    "hidden",
    "hollow",
    "honest",
    "humble",
    "iron",
    "ivory",
    "jade",
    "jolly",
    "keen",
    "kind",
    "lake",
    "laser",
    "leafy",
    "light",
    "lime",
    "little",
    "lively",
    "loyal",
    "lucky",
    "lunar",
    "magic",
    "maple",
    "mellow",
    "misty",
    "mossy",
    "mount",
    "mute",
    "neat",
    "nimble",
    "noble",
    "north",
    "ocean",
    "olive",
    "opal",
    "pale",
    "peace",
    "pearl",
    "pine",
    "plain",
    "polar",
    "proud",
    "pure",
    "quick",
    "quiet",
    "rapid",
    "rare",
    "red",
    "rich",
    "river",
    "rocky",
    "rosy",
    "rough",
    "round",
    "royal",
    "ruby",
    "rusty",
    "sandy",
    "serene",
    "sharp",
    "shining",
    "silent",
    "silver",
    "simple",
    "sleek",
    "solar",
    "solid",
    "south",
    "spark",
    "steady",
    "stone",
    "stormy",
    "stout",
    "strong",
    "summer",
    "sunny",
    "super",
    "swift",
    "tall",
    "tidy",
    "timber",
    "tiny",
    "topaz",
    "tough",
    "true",
    "twin",
    "urban",
    "valiant",
    "vast",
    "velvet",
    "vibrant",
    "violet",
    "vivid",
    "warm",
    "wild",
    "winter",
    "wise",
]

NOUNS = [
    "badger",
    "falcon",
    "beacon",
    "bear",
    "beaver",
    "bison",
    "breeze",
    "brook",
    "canyon",
    "castle",
    "cedar",
    "cliff",
    "comet",
    "compass",
    "condor",
    "crane",
    "creek",
    "crag",
    "delta",
    "diver",
    "dolphin",
    "dragon",
    "eagle",
    "echo",
    "elk",
    "ember",
    "falcon",
    "feather",
    "finch",
    "fjord",
    "flame",
    "forest",
    "fox",
    "frost",
    "garden",
    "glade",
    "glider",
    "gorge",
    "grove",
    "gull",
    "harbor",
    "haven",
    "hawk",
    "heron",
    "island",
    "jaguar",
    "jetty",
    "kite",
    "koala",
    "lagoon",
    "lark",
    "leopard",
    "lynx",
    "mantis",
    "meadow",
    "meteor",
    "monarch",
    "moose",
    "mountain",
    "nebula",
    "nest",
    "newt",
    "oasis",
    "orbit",
    "orca",
    "osprey",
    "otter",
    "owl",
    "panther",
    "parrot",
    "peak",
    "pelican",
    "penguin",
    "phoenix",
    "pine",
    "pioneer",
    "planet",
    "plateau",
    "plover",
    "prism",
    "quail",
    "quarry",
    "quartz",
    "rabbit",
    "raptor",
    "raven",
    "reef",
    "ridge",
    "river",
    "robin",
    "rover",
    "sable",
    "sailor",
    "salmon",
    "sanctuary",
    "scout",
    "seagull",
    "seal",
    "shadow",
    "shark",
    "shelter",
    "signal",
    "sparrow",
    "sphere",
    "stream",
    "summit",
    "swift",
    "talon",
    "thicket",
    "tiger",
    "timber",
    "torch",
    "tower",
    "trail",
    "tundra",
    "valley",
    "vessel",
    "viper",
    "voyager",
    "walrus",
    "wave",
    "willow",
    "wolf",
    "wombat",
    "wren",
    "yarrow",
    "zenith",
    "zephyr",
]


def generate_code(min_number: int = 1, max_number: int = 99) -> str:
    """Generates a random code phrase such as '7-copper-falcon'."""
    number = secrets.randbelow(max_number - min_number + 1) + min_number
    adjective = secrets.choice(ADJECTIVES)
    noun = secrets.choice(NOUNS)
    return f"{number}-{adjective}-{noun}"


def parse_code(code: str) -> Tuple[int, str, str]:
    """Parses and validates a code phrase.

    Raises ValueError if format does not match number-word-word.
    """
    parts = code.strip().lower().split("-")
    if len(parts) != 3:
        raise ValueError(f"Invalid code format: '{code}'. Expected format like '7-copper-falcon'")

    number_str, adj, noun = parts
    try:
        number = int(number_str)
    except ValueError as err:
        raise ValueError(f"Code prefix must be an integer: '{number_str}'") from err

    return number, adj, noun


def validate_code(code: str) -> bool:
    """Returns True if the string matches the expected code phrase format."""
    try:
        parse_code(code)
        return True
    except ValueError:
        return False
